-- USER 테이블

-- 테이블 삭제 
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE USERS (
   USER_ID VARCHAR2(250),
   PASSWORD VARCHAR2(250) ,
   USER_NAME VARCHAR2(100) NOT NULL,
   NICK_NAME VARCHAR2(50),
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(50),
   BIRTH_DATE DATE,
   USER_TYPE CHAR(1) DEFAULT 'U' NOT NULL,
   GENDER CHAR(1),
   PROFILE_URL VARCHAR2(150),
   LOGIN_TIME TIMESTAMP,
   login_type VARCHAR2(50),
   sns_access_token VARCHAR2(150),
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
   CONSTRAINT UNQ_USER_EMAIL UNIQUE (EMAIL),
   CONSTRAINT CHK_USER_TYPE CHECK (USER_TYPE IN ('U','A','D')),
   CONSTRAINT CHK_GENDER CHECK (GENDER IN ('M', 'F'))
);

--테이블 주석
COMMENT ON TABLE USERS IS '유저 관리';

COMMENT ON COLUMN USERS.USER_ID IS '아이디';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS '이름';
COMMENT ON COLUMN USERS.NICK_NAME IS '닉네임';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.PHONE IS '전화번호';
COMMENT ON COLUMN USERS.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN USERS.USER_TYPE IS '회원 타입';
COMMENT ON COLUMN USERS.GENDER IS '성별';
COMMENT ON COLUMN USERS.PROFILE_URL IS '프로필 URL';

-- 인덱스 추가
CREATE INDEX IDX_USER_PHONE ON USERS (PHONE);


-- TOKEN_LOGIN 테이블

-- 인덱스와 테이블 삭제

ALTER TABLE TOKEN_LOGIN DROP CONSTRAINT PK_TOKEN_LOGIN;

DROP TABLE TOKEN_LOGIN CASCADE CONSTRAINTS;

CREATE TABLE TOKEN_LOGIN (
   USER_ID VARCHAR2(50) NOT NULL,
   ACCESSTOKEN VARCHAR2(255),
   REFRESHTOKEN VARCHAR2(255),
   ACCESS_CREATED DATE,
   ACCESS_EXPIRES DATE,
   REFRESH_EXPIRES DATE,
   REFRESH_CREATED DATE
);

COMMENT ON TABLE TOKEN_LOGIN IS '토큰';

COMMENT ON COLUMN TOKEN_LOGIN.USER_ID IS '유저아이디';

COMMENT ON COLUMN TOKEN_LOGIN.ACCESSTOKEN IS '인증토큰';

COMMENT ON COLUMN TOKEN_LOGIN.REFRESHTOKEN IS '만료토큰';

COMMENT ON COLUMN TOKEN_LOGIN.ACCESS_CREATED IS '토큰 생성 시간';

COMMENT ON COLUMN TOKEN_LOGIN.ACCESS_EXPIRES IS '액세스 토큰 만료 시간';

COMMENT ON COLUMN TOKEN_LOGIN.REFRESH_EXPIRES IS '리프레시 토큰 만료 시간';

COMMENT ON COLUMN TOKEN_LOGIN.REFRESH_CREATED IS '리프레시 토큰 생성 시간';

-- 기본 키 제약 조건 추가
ALTER TABLE TOKEN_LOGIN
   ADD CONSTRAINT PK_TOKEN_LOGIN PRIMARY KEY (USER_ID);

-- 외래 키 제약 조건 추가
ALTER TABLE TOKEN_LOGIN
   ADD CONSTRAINT FK_USERS_TO_TOKEN_LOGIN FOREIGN KEY (USER_ID)
   REFERENCES USERS (USER_ID);


-- SOCIALLOGINS 테이블

-- 인덱스와 테이블 삭제
--DROP INDEX PK_SOCIALLOGINS;

DROP TABLE SOCIALLOGINS CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE SOCIALLOGINS (
    SOCIALUSERID VARCHAR2(255) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    SOCIALSITE VARCHAR2(50) NOT NULL CHECK (SOCIALSITE IN ('Naver', 'Kakao')),
    LOGIN_TIME DATE NOT NULL
);

-- 테이블 주석
COMMENT ON TABLE SOCIALLOGINS IS '소셜로그인';

COMMENT ON COLUMN SOCIALLOGINS.SOCIALUSERID IS '플렛폼 아이디';

COMMENT ON COLUMN SOCIALLOGINS.USER_ID IS '아이디';

COMMENT ON COLUMN SOCIALLOGINS.SOCIALSITE IS '플렛폼 이름';

COMMENT ON COLUMN SOCIALLOGINS.LOGIN_TIME IS '로그인 시간';

-- 복합 기본 키 생성
CREATE UNIQUE INDEX PK_SOCIALLOGINS ON SOCIALLOGINS (SOCIALUSERID ASC, USER_ID ASC);

ALTER TABLE SOCIALLOGINS ADD CONSTRAINT PK_SOCIALLOGINS PRIMARY KEY (SOCIALUSERID, USER_ID);

-- 외래 키 제약조건
ALTER TABLE SOCIALLOGINS ADD CONSTRAINT FK_USERS_TO_SOCIALLOGINS_1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);


-- INQUIRY 테이블

-- 시퀀스 삭제
DROP SEQUENCE INQUIRY_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE INQUIRY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;

-- 인덱스와 테이블 삭제를 위해 먼저 기본 키 제약 조건 삭제
ALTER TABLE INQUIRY DROP CONSTRAINT PK_INQUIRY;

-- 인덱스 삭제
--DROP INDEX PK_INQUIRY;

-- 테이블 삭제
DROP TABLE INQUIRY CASCADE CONSTRAINTS;


-- 테이블 생성
CREATE TABLE INQUIRY (
    INQUIRY_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(250) NOT NULL,
    CONTENT VARCHAR2(3000) NOT NULL,
    INQUIRY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(50) DEFAULT '미처리' CHECK (STATUS IN ('미처리', '처리중', '완료')) 
);

-- 테이블 주석
COMMENT ON TABLE INQUIRY IS '문의사항';

COMMENT ON COLUMN INQUIRY.INQUIRY_NO IS '문의 번호';

COMMENT ON COLUMN INQUIRY.USER_ID IS '작성자'; 

COMMENT ON COLUMN INQUIRY.TITLE IS '제목';

COMMENT ON COLUMN INQUIRY.CONTENT IS '내용';

COMMENT ON COLUMN INQUIRY.INQUIRY_DATE IS '등록날짜';

COMMENT ON COLUMN INQUIRY.STATUS IS '처리여부';


CREATE UNIQUE INDEX PK_INQUIRY ON INQUIRY (INQUIRY_NO ASC);

ALTER TABLE INQUIRY ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (INQUIRY_NO);

ALTER TABLE INQUIRY ADD CONSTRAINT FK_USERS_TO_INQUIRY FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID); 

COMMIT;