-- 더미 데이터 삽입
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user01', 'password01', '홍길동', 'hong', 'hong01@example.com', '010-1234-5678', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile01', SYSTIMESTAMP, 'email', 'token01');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user02', 'password02', '이몽룡', 'lee', 'lee02@example.com', '010-2345-6789', TO_DATE('1985-02-02', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile02', SYSTIMESTAMP, 'email', 'token02');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user03', 'password03', '성춘향', 'sung', 'sung03@example.com', '010-3456-7890', TO_DATE('1992-03-03', 'YYYY-MM-DD'), 'U', 'F', 'http://example.com/profile03', SYSTIMESTAMP, 'email', 'token03');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user04', 'password04', '변사또', 'byun', 'byun04@example.com', '010-4567-8901', TO_DATE('1980-04-04', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile04', SYSTIMESTAMP, 'email', 'token04');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user05', 'password05', '김철수', 'kim', 'kim05@example.com', '010-5678-9012', TO_DATE('1995-05-05', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile05', SYSTIMESTAMP, 'email', 'token05');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user06', 'password06', '박영희', 'park', 'park06@example.com', '010-6789-0123', TO_DATE('1993-06-06', 'YYYY-MM-DD'), 'U', 'F', 'http://example.com/profile06', SYSTIMESTAMP, 'email', 'token06');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user07', 'password07', '최길동', 'choi', 'choi07@example.com', '010-7890-1234', TO_DATE('1988-07-07', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile07', SYSTIMESTAMP, 'email', 'token07');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user08', 'password08', '한지민', 'han', 'han08@example.com', '010-8901-2345', TO_DATE('1997-08-08', 'YYYY-MM-DD'), 'U', 'F', 'http://example.com/profile08', SYSTIMESTAMP, 'email', 'token08');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user09', 'password09', '정우성', 'jung', 'jung09@example.com', '010-9012-3456', TO_DATE('1983-09-09', 'YYYY-MM-DD'), 'U', 'M', 'http://example.com/profile09', SYSTIMESTAMP, 'email', 'token09');
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, NICK_NAME, EMAIL, PHONE, BIRTH_DATE, USER_TYPE, GENDER, PROFILE_URL, LOGIN_TIME, LOGIN_TYPE, SNS_ACCESS_TOKEN) VALUES
('user10', 'password10', '이영애', 'lee', 'lee10@example.com', '010-0123-4567', TO_DATE('1991-10-10', 'YYYY-MM-DD'), 'U', 'F', 'http://example.com/profile10', SYSTIMESTAMP, 'email', 'token10');
